## Table captions
## Summary
caption_tab_ssu("ssu_beta_disp_tests", "Summary of Beta Dispersion Tests for unfiltered & filtered data sets against various distance metrics. The `test` column shows the method chosen (based on the test results) to assess differences in beta diversity. If p-values are significant (red, p-value < 0.05) we used ANOSIM, otherwise we used PERMANOVA (blue, p-value > 0.05).")
caption_tab_ssu("ssu_tab_sig_test_full", "Summary of significant tests by Year for FULL,   unfiltered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_filt", "Summary of significant tests by Year for Arbitrary filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_perfect", "Summary of significant tests by Year for PERFect filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_pime", "Summary of significant tests by Year for PIME filtered data set. P-values in red indicate significant differences (p-value < 0.05).")

caption_tab_its("its_beta_disp_tests", "Summary of Beta Dispersion Tests for unfiltered & filtered data sets against various distance metrics. The `test` column shows the method chosen (based on the test results) to assess differences in beta diversity. If p-values are significant (red, p-value < 0.05) we used ANOSIM, otherwise we used PERMANOVA (blue, p-value > 0.05).")
caption_tab_its("its_tab_sig_test_full", "Summary of significant tests by Year for FULL, unfiltered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_filt", "Summary of significant tests by Year for Arbitrary filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_perfect", "Summary of significant tests by Year for PERFect filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_pime", "Summary of significant tests by Year for PIME filtered data set. P-values in red indicate significant differences (p-value < 0.05).")


caption_tab_ssu("ssu_tab_sig_test_age_full", "Summary of significant tests for forest age within each Year and Treatment for FULL, unfiltered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_age_filt", "Summary of significant tests for forest age within each Year and Treatment for for Arbitrary filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_age_perfect", "Summary of significant tests for forest age within each Year and Treatment for PERFect filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_age_pime", "Summary of significant tests for forest age within each Year and Treatment for PIME filtered data set. P-values in red indicate significant differences (p-value < 0.05).")

caption_tab_its("its_tab_sig_test_age_full", "Summary of significant tests for forest age within each Year and Treatment for FULL, unfiltered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_age_filt", "Summary of significant tests for forest age within each Year and Treatment for for Arbitrary filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_age_perfect", "Summary of significant tests for forest age within each Year and Treatment for PERFect filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_age_pime", "Summary of significant tests for forest age within each Year and Treatment for PIME filtered data set. P-values in red indicate significant differences (p-value < 0.05).")


#<small>`r caption_tab_ssu("qual_scores_after_ssu")`</small>

## Figure captions
caption_fig_ssu("ssu_beta_div_plots_full", "FULL data set PCoA ordination plots of various distance methods across three sampling years. ")
caption_fig_ssu("ssu_beta_div_plots_filt", "Arbitrary filtered data set PCoA ordination plots of various distance methods across three sampling years. ")
caption_fig_ssu("ssu_beta_div_plots_perfect", "PERfect filtered data set PCoA ordination plots of various distance methods across three sampling years. ")
caption_fig_ssu("ssu_beta_div_plots_pime", "PIME filtered data set PCoA ordination plots of various distance methods across three sampling years. ")

caption_fig_ssu("ssu_ps_work_jaccard_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_work_jsd_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_work_unwei_unifrac_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_work_wei_unifrac_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_ssu("ssu_ps_filt_jaccard_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_filt_jsd_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_filt_unwei_unifrac_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_filt_wei_unifrac_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_ssu("ssu_ps_perfect_jaccard_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_perfect_jsd_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_perfect_unwei_unifrac_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_perfect_wei_unifrac_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_ssu("ssu_ps_pime_jaccard_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_pime_jsd_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_pime_unwei_unifrac_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_pime_wei_unifrac_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_its("its_beta_div_plots_full", "FULL data set PCoA ordination plots of various distance methods across three sampling years. ")
caption_fig_its("its_beta_div_plots_filt", "Arbitrary filtered data set PCoA ordination plots of various distance methods across three sampling years. ")
caption_fig_its("its_beta_div_plots_perfect", "PERfect filtered data set PCoA ordination plots of various distance methods across three sampling years. ")
caption_fig_its("its_beta_div_plots_pime", "PIME filtered data set PCoA ordination plots of various distance methods across three sampling years. ")

caption_fig_its("its_ps_work_bray_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_work_jaccard_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_work_jsd_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_work_gower_me_variation_plots", "Pairwise group variation plots of the FULL data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_its("its_ps_filt_bray_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_filt_jaccard_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_filt_jsd_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_filt_gower_me_variation_plots", "Pairwise group variation plots of the Arbitrary filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_its("its_ps_perfect_bray_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_perfect_jaccard_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_perfect_jsd_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_perfect_gower_me_variation_plots", "Pairwise group variation plots of the PERFect filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_its("its_ps_pime_bray_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_pime_jaccard_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_pime_jsd_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_pime_gower_me_variation_plots", "Pairwise group variation plots of the PIME filtered data set across sampling years. Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

#<small>`r caption_fig_ssu("ssu_alpha_div_plots")`</small>

# OLD

#caption_fig_ssu("ssu_ps_work_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_work_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_work_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_filt_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_filt_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_filt_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_perfect_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_perfect_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_perfect_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_pime_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_pime_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_ssu("ssu_ps_pime_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#
#caption_fig_its("its_ps_work_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_work_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_work_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_filt_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_filt_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_filt_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_perfect_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_perfect_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_perfect_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_pime_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_pime_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
#caption_fig_its("its_ps_pime_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
